[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "yks-music"
version = "0.1.0"
description = "CLI interativo para baixar músicas do YouTube com yt-dlp"
authors = [
    { name = "Yuki", email = "yuki@example.com" }
]
requires-python = ">=3.7"
dependencies = [
    "rich>=12.0",
    "pyfiglet>=0.8",
    "prompt_toolkit>=3.0",
    "yt-dlp",
    "mutagen",
    "pillow",
]

[project.scripts]
yks-music = "yks_music.cli:main"

[tool.setuptools.packages.find]
where = ["."]
